name: validation workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - name: validation
        run: |
          exit ${{ vars.prod_status }}
